//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bed_pngrepo_com {
            get {
                object obj = ResourceManager.GetObject("bed-pngrepo-com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_1 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_2 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_3 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_4 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_pogled_1 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna pogled 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_pogled_2 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna pogled 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_pogled_3 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna pogled 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dvokrevetna_pogled_4 {
            get {
                object obj = ResourceManager.GetObject("Dvokrevetna pogled 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap guest_pngrepo_com {
            get {
                object obj = ResourceManager.GetObject("guest-pngrepo-com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jednokrevetna_pogled_1 {
            get {
                object obj = ResourceManager.GetObject("Jednokrevetna pogled 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jednokrevetna_pogled_2 {
            get {
                object obj = ResourceManager.GetObject("Jednokrevetna pogled 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jednokrevetna_pogled_3 {
            get {
                object obj = ResourceManager.GetObject("Jednokrevetna pogled 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Jednokrevetna_pogled_4 {
            get {
                object obj = ResourceManager.GetObject("Jednokrevetna pogled 4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kisspng_india_login_computer_icons_emoticon_medicine_user_login_icon_5ab05c8c27d4c1_4591099815215074681632 {
            get {
                object obj = ResourceManager.GetObject("kisspng-india-login-computer-icons-emoticon-medicine-user-login-icon-5ab05c8c27d4" +
                        "c1.4591099815215074681632", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Odvojena_Dvokrevetna_1 {
            get {
                object obj = ResourceManager.GetObject("Odvojena Dvokrevetna 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Odvojena_Dvokrevetna_2 {
            get {
                object obj = ResourceManager.GetObject("Odvojena Dvokrevetna 2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Odvojena_Dvokrevetna_3 {
            get {
                object obj = ResourceManager.GetObject("Odvojena Dvokrevetna 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reservation_icon_png_29 {
            get {
                object obj = ResourceManager.GetObject("reservation-icon-png-29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap staff_pngrepo_com {
            get {
                object obj = ResourceManager.GetObject("staff-pngrepo-com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
